FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Pleb

**Hello World!!**

## Hello [/name]
Just rndm bullshit **name**

### Name [GET]

+ Response 200 (application/json) 
        {
            "name":"World" 
         }